### ISSUE TITLE
Našeptávání

### ISSUE THREAD

**Issue by vojkny** [Mikulas/nette-forms-taginput#13]
TagInput používám v controlu, který si sám v sobě buduje formulář. Problém je ten, že pokud našeptávání tímhle způsobem negeneruje odkaz na současný presenter/komponentu, ale na na root, tedy /?word_filter=... 

Také úplně nerozumím tomu, kdy se má našeptávání generovat, pokud není posílán žádný signál, ale pouze parametr "word_filter". Uvedl bys mě prosím v pravdu? :-)

**Comment by Mikulas** [comment]
Asi chápu co myslíš. Našeptávání je imho totiž úplně špatně vyřešené, stejně tak obal javascriptu : ). Verze 2.0 je jenom přepsaný js, aby byl hezký uvnitř a hlavně aby přežil ajaxové hrátky (tzn. snippety). Unobstr. a tohle **budu řešit časem**, teď mě vytěžuje všechno ostatní. Nechávám to otevřené a časem to bude.
